package monedas;

public enum Monedas {
    AFGANISTAN("Afghani Afgano", "AFN", "Afganistán"),
    ALBANIA("Lek Albanés", "ALL", "Albania"),
    ALEMANIA("Euro", "EUR", "Alemania"),
    ARGELIA("Dinar Argelino", "DZD", "Argelia"),
    ARGENTINA("Peso Argentino", "ARS", "Argentina"),
    ARMENIA("Dram Armenio", "AMD", "Armenia"),
    ARUBA("Florín Arubano", "AWG", "Aruba"),
    AUSTRALIA("Dólar Australiano", "AUD", "Australia"),
    AZERBAIYAN("Manat Azerbaiyano", "AZN", "Azerbaiyán"),
    BAHAMAS("Dólar Bahameño", "BSD", "Bahamas"),
    BAHREIN("Dinar Bareiní", "BHD", "Bahréin"),
    BANGLADESH("Taka Bangladeshí", "BDT", "Bangladesh"),
    BARBADOS("Dólar de Barbados", "BBD", "Barbados"),
    BELGICA("Euro", "EUR", "Bélgica"),
    BELICE("Dólar Beliceño", "BZD", "Belice"),
    BENIN("Franco CFA de África Occidental", "XOF", "Benín"),
    BIELORRUSIA("Rublo Bielorruso", "BYN", "Bielorrusia"),
    BIRMANIA("Kyat Birmano", "MMK", "Birmania"),
    BOLIVIA("Boliviano", "BOB", "Bolivia"),
    BOSNIA_HERZEGOVINA("Marco de Bosnia y Herzegovina", "BAM", "Bosnia y Herzegovina"),
    BOTSUANA("Pula Botsuano", "BWP", "Botsuana"),
    BRASIL("Real Brasileño", "BRL", "Brasil"),
    BRUNEI("Dólar de Brunéi", "BND", "Brunéi"),
    BULGARIA("Lev Búlgaro", "BGN", "Bulgaria"),
    BURUNDI("Franco Burundés", "BIF", "Burundi"),
    BUTAN("Ngultrum Butanés", "BTN", "Bután"),
    CABO_VERDE("Escudo Caboverdiano", "CVE", "Cabo Verde"),
    CAMBOYA("Riel Camboyano", "KHR", "Camboya"),
    CAMERUN("Franco CFA de África Central", "XAF", "Camerún"),
    CANADA("Dólar Canadiense", "CAD", "Canadá"),
    CATAR("Riyal Catarí", "QAR", "Catar"),
    CHAD("Franco CFA de África Central", "XAF", "Chad"),
    CHILE("Peso Chileno", "CLP", "Chile"),
    CHINA("Yuan Renminbi", "CNY", "China"),
    CHIPRE("Euro", "EUR", "Chipre"),
    COLOMBIA("Peso Colombiano", "COP", "Colombia"),
    COMORAS("Franco Comorano", "KMF", "Comoras"),
    CONGO_DEM("Franco Congoleño", "CDF", "República Democrática del Congo"),
    COREA_DEL_SUR("Won Surcoreano", "KRW", "Corea del Sur"),
    COSTA_RICA("Colón Costarricense", "CRC", "Costa Rica"),
    CROACIA("Kuna Croata", "HRK", "Croacia"),
    CUBA("Peso Cubano", "CUP", "Cuba"),
    DINAMARCA("Corona Danesa", "DKK", "Dinamarca"),
    DJIBOUTI("Franco Yibutiano", "DJF", "Yibuti"),
    DOMINICA("Dólar del Caribe Oriental", "XCD", "Dominica"),
    ECUADOR("Dólar Estadounidense", "USD", "Ecuador"),
    EGIPTO("Libra Egipcia", "EGP", "Egipto"),
    EL_SALVADOR("Dólar Estadounidense", "USD", "El Salvador"),
    EMIRATOS_ARABES_UNIDOS("Dirham de los EAU", "AED", "Emiratos Árabes Unidos"),
    ERITREA("Nakfa Eritreo", "ERN", "Eritrea"),
    ESLOVAQUIA("Euro", "EUR", "Eslovaquia"),
    ESLOVENIA("Euro", "EUR", "Eslovenia"),
    ESPANA("Euro", "EUR", "España"),
    ESTADOS_UNIDOS("Dólar Estadounidense", "USD", "Estados Unidos"),
    ESTONIA("Euro", "EUR", "Estonia"),
    ETIOPIA("Birr Etíope", "ETB", "Etiopía"),
    FILIPINAS("Peso Filipino", "PHP", "Filipinas"),
    FINLANDIA("Euro", "EUR", "Finlandia"),
    FIYI("Dólar Fiyiano", "FJD", "Fiyi"),
    FRANCIA("Euro", "EUR", "Francia"),
    GABON("Franco CFA de África Central", "XAF", "Gabón"),
    GAMBIA("Dalasi Gambiano", "GMD", "Gambia"),
    GEORGIA("Lari Georgiano", "GEL", "Georgia"),
    GHANA("Cedi Ghanés", "GHS", "Ghana"),
    GIBRALTAR("Libra de Gibraltar", "GIP", "Gibraltar"),
    GRANADA("Dólar del Caribe Oriental", "XCD", "Granada"),
    GRECIA("Euro", "EUR", "Grecia"),
    GUATEMALA("Quetzal Guatemalteco", "GTQ", "Guatemala"),
    GUINEA("Franco Guineano", "GNF", "Guinea"),
    GUYANA("Dólar Guyanés", "GYD", "Guyana"),
    HAITI("Gourde Haitiano", "HTG", "Haití"),
    HONDURAS("Lempira Hondureño", "HNL", "Honduras"),
    HONG_KONG("Dólar de Hong Kong", "HKD", "Hong Kong"),
    HUNGRIA("Forinto Húngaro", "HUF", "Hungría"),
    INDIA("Rupia India", "INR", "India"),
    INDONESIA("Rupia Indonesia", "IDR", "Indonesia"),
    IRAK("Dinar Iraquí", "IQD", "Irak"),
    IRAN("Rial Iraní", "IRR", "Irán"),
    IRLANDA("Euro", "EUR", "Irlanda"),
    ISLANDIA("Corona Islandesa", "ISK", "Islandia"),
    ISRAEL("Nuevo Shekel Israelí", "ILS", "Israel"),
    ITALIA("Euro", "EUR", "Italia"),
    JAMAICA("Dólar Jamaiquino", "JMD", "Jamaica"),
    JAPON("Yen Japonés", "JPY", "Japón"),
    JERSEY("Libra de Jersey", "JEP", "Jersey"),
    JORDANIA("Dinar Jordano", "JOD", "Jordania"),
    KAZAJISTAN("Tenge Kazajo", "KZT", "Kazajistán"),
    KENIA("Chelín Keniata", "KES", "Kenia"),
    KIRGUISTAN("Som Kirguís", "KGS", "Kirguistán"),
    KIRIBATI("Dólar de Kiribati", "KID", "Kiribati"),
    KUWAIT("Dinar Kuwaití", "KWD", "Kuwait"),
    LAOS("Kip Lao", "LAK", "Laos"),
    LESOTO("Loti Lesotense", "LSL", "Lesoto"),
    LETONIA("Euro", "EUR", "Letonia"),
    LIBANO("Libra Libanesa", "LBP", "Líbano"),
    LIBERIA("Dólar Liberiano", "LRD", "Liberia"),
    LIBIA("Dinar Libio", "LYD", "Libia"),
    LITUANIA("Euro", "EUR", "Lituania"),
    LUXEMBURGO("Euro", "EUR", "Luxemburgo"),
    MACEDONIA_DEL_NORTE("Denar Macedonio", "MKD", "Macedonia del Norte"),
    MADAGASCAR("Ariary Malgache", "MGA", "Madagascar"),
    MALASIA("Ringgit Malayo", "MYR", "Malasia"),
    MALAWI("Kwacha Malauí", "MWK", "Malawi"),
    MALDIVAS("Rufiyaa Maldiva", "MVR", "Maldivas"),
    MALI("Franco CFA de África Occidental", "XOF", "Malí"),
    MALTA("Euro", "EUR", "Malta"),
    MARRUECOS("Dírham Marroquí", "MAD", "Marruecos"),
    MAURICIO("Rupia Mauriciana", "MUR", "Mauricio"),
    MAURITANIA("Ouguiya Mauritana", "MRU", "Mauritania"),
    MEXICO("Peso Mexicano", "MXN", "México"),
    MOLDAVIA("Leu Moldavo", "MDL", "Moldavia"),
    MONACO("Euro", "EUR", "Mónaco"),
    MONGOLIA("Tögrög Mongol", "MNT", "Mongolia"),
    MONTENEGRO("Euro", "EUR", "Montenegro"),
    MOZAMBIQUE("Metical Mozambiqueño", "MZN", "Mozambique"),
    NAMIBIA("Dólar Namibio", "NAD", "Namibia"),
    NEPAL("Rupia Nepalí", "NPR", "Nepal"),
    NICARAGUA("Córdoba Nicaragüense", "NIO", "Nicaragua"),
    NIGER("Franco CFA de África Occidental", "XOF", "Níger"),
    NIGERIA("Naira Nigeriana", "NGN", "Nigeria"),
    NORUEGA("Corona Noruega", "NOK", "Noruega"),
    NUEVA_ZELANDA("Dólar Neozelandés", "NZD", "Nueva Zelanda"),
    OMAN("Rial Omaní", "OMR", "Omán"),
    PAISES_BAJOS("Euro", "EUR", "Países Bajos"),
    PAKISTAN("Rupia Pakistaní", "PKR", "Pakistán"),
    PALAOS("Dólar Estadounidense", "USD", "Palaos"),
    PANAMA("Balboa Panameño", "PAB", "Panamá"),
    PAPUA_NUEVA_GUINEA("Kina Papúa Nueva Guineana", "PGK", "Papúa Nueva Guinea"),
    PARAGUAY("Guaraní Paraguayo", "PYG", "Paraguay"),
    PERU("Sol Peruano", "PEN", "Perú"),
    POLONIA("Złoty Polaco", "PLN", "Polonia"),
    PORTUGAL("Euro", "EUR", "Portugal"),
    QATAR("Riyal Catarí", "QAR", "Qatar"),
    REINO_UNIDO("Libra Esterlina", "GBP", "Reino Unido"),
    REPUBLICA_CHECA("Corona Checa", "CZK", "República Checa"),
    REPUBLICA_DOMINICANA("Peso Dominicano", "DOP", "República Dominicana"),
    RUANDA("Franco Ruandés", "RWF", "Ruanda"),
    RUMANIA("Leu Rumano", "RON", "Rumanía"),
    RUSIA("Rublo Ruso", "RUB", "Rusia"),
    SAHARA_OCCIDENTAL("Dírham Marroquí", "MAD", "Sahara Occidental"),
    SAMOA("Tālā Samoano", "WST", "Samoa"),
    SAN_CRISTOBAL_Y_NIEVES("Dólar del Caribe Oriental", "XCD", "San Cristóbal y Nieves"),
    SAN_MARINO("Euro", "EUR", "San Marino"),
    SANTA_LUCIA("Dólar del Caribe Oriental", "XCD", "Santa Lucía"),
    SANTO_TOME_Y_PRINCIPE("Dobra de Santo Tomé y Príncipe", "STN", "Santo Tomé y Príncipe"),
    SENEGAL("Franco CFA de África Occidental", "XOF", "Senegal"),
    SERBIA("Dinar Serbio", "RSD", "Serbia"),
    SEYCHELLES("Rupia de Seychelles", "SCR", "Seychelles"),
    SIERRA_LEONA("Leone de Sierra Leona", "SLE", "Sierra Leona"),
    SINGAPUR("Dólar de Singapur", "SGD", "Singapur"),
    SIRIA("Libra Siria", "SYP", "Siria"),
    SOMALIA("Chelín Somalí", "SOS", "Somalia"),
    SRI_LANKA("Rupia de Sri Lanka", "LKR", "Sri Lanka"),
    SUDAFRICA("Rand Sudafricano", "ZAR", "Sudáfrica"),
    SUDAN("Libra Sudanesa", "SDG", "Sudán"),
    SUECIA("Corona Sueca", "SEK", "Suecia"),
    SUIZA("Franco Suizo", "CHF", "Suiza"),
    SURINAM("Dólar Surinamés", "SRD", "Surinam"),
    TAILANDIA("Baht Tailandés", "THB", "Tailandia"),
    TAIWAN("Nuevo Dólar Taiwanés", "TWD", "Taiwán"),
    TANZANIA("Chelín Tanzano", "TZS", "Tanzania"),
    TAYIKISTAN("Somoni Tayiko", "TJS", "Tayikistán"),
    TIMOR_ORIENTAL("Dólar Estadounidense", "USD", "Timor Oriental"),
    TOGO("Franco CFA de África Occidental", "XOF", "Togo"),
    TONGA("Paʻanga Tongano", "TOP", "Tonga"),
    TRINIDAD_Y_TOBAGO("Dólar de Trinidad y Tobago", "TTD", "Trinidad y Tobago"),
    TUNEZ("Dinar Tunecino", "TND", "Túnez"),
    TURKMENISTAN("Manat Turcomano", "TMT", "Turkmenistán"),
    TURQUIA("Lira Turca", "TRY", "Turquía"),
    TUVALU("Dólar Tuvaluano", "TVD", "Tuvalu"),
    UCRANIA("Grivna Ucraniana", "UAH", "Ucrania"),
    UGANDA("Chelín Ugandés", "UGX", "Uganda"),
    URUGUAY("Peso Uruguayo", "UYU", "Uruguay"),
    UZBEKISTAN("Som Uzbeko", "UZS", "Uzbekistán"),
    VANUATU("Vatu Vanuatuense", "VUV", "Vanuatu"),
    VENEZUELA("Bolívar Soberano Venezolano", "VES", "Venezuela"),
    VIETNAM("Dong Vietnamita", "VND", "Vietnam"),
    YEMEN("Rial Yemení", "YER", "Yemen"),
    ZAMBIA("Kwacha Zambiano", "ZMW", "Zambia"),
    ZIMBABUE("Dólar Zimbabuense", "ZWL", "Zimbabue");

    private String nombreDeLaMoneda;
    private String acronimo;
    private String pais;

    Monedas(String nombreDeLaMoneda, String acronimo, String pais) {
        this.nombreDeLaMoneda = nombreDeLaMoneda;
        this.acronimo = acronimo;
        this.pais = pais;
    }

    public String getNombreDeLaMoneda() {
        return nombreDeLaMoneda;
    }

    public String getAcronimo() {
        return acronimo;
    }

    public String getPais() {
        return pais;
    }
}
